### ISSUE TITLE
mapping spatial coordinates in `coord_sf()`

### ISSUE THREAD

**Issue by hkeys999** [qdread/qdrmapbox#1]
Hi Quentin,

You may remember me from contacting you in the past about your qdrmapbox package - beautiful tool! 

I recently ran the code again (no changes at all based on your original blog post), and for some reason I get the following error message:

Error in `calc_limits_bbox()`:
! Scale limits cannot be mapped onto spatial coordinates in `coord_sf()`
ℹ Consider setting `lims_method = "geometry_bbox"` or `default_crs = NULL`.
Run `rlang::last_trace()` to see where the error occurred.

I ran a backtrace to get this:

Backtrace:
     ▆
  1. ├─base (local) `<fn>`(x)
  2. └─ggplot2:::print.ggplot(x)
  3.   ├─ggplot2::ggplot_build(x)
  4.   └─ggplot2:::ggplot_build.ggplot(x)
  5.     └─layout$setup_panel_params()
  6.       └─ggplot2 (local) setup_panel_params(..., self = self)
  7.         └─base::Map(setup_panel_params, scales_x, scales_y)
  8.           └─base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  9.             └─ggplot2 (local) `<fn>`(dots[[1L]][[1L]], dots[[2L]][[1L]])
 10.               └─self$coord$setup_panel_params(scale_x, scale_y, params = self$coord_params)
 11.                 └─ggplot2 (local) setup_panel_params(..., self = self)
 12.                   └─ggplot2:::calc_limits_bbox(self$lims_method, scale_xlim, scale_ylim, params$crs, params$default_crs)
 13.                     └─cli::cli_abort(...)
 14.                       └─rlang::abort(...)

Any suggestions or tips to understanding this? Obviously, I'm a novice R user, so apologies for formatting issues.

**Comment by qdread** [comment]
Hi there, I just updated all my R packages to the latest versions and ran the R code from the blog post again. It worked correctly. Can you please try updating all packages and running the code again, to see if you still get the error? Also please let me know what line of code resulted in the error. Thanks!

**Comment by hkeys999** [comment]
Hi Quentin,

Thanks for fast reply. I updated all packages. 

The error message comes after executing the final command to build the image (using your code):

ggplot() +
  annotation_spatial(data = mdimage_raster, alpha = 0.9)

**Comment by qdread** [comment]
After loading all the packages, please call `sessionInfo()` and paste the output in a comment so I can see what versions of everything you have.

**Comment by hkeys999** [comment]
Thanks for quick reply as always. I believe all is updated (quite a few other packages given other graphics and touches I add):

─ Packages ───────────────────────────────────────────────────────────────────────────────
 package       * version date (UTC) lib source
 assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.2.0)
 backports       1.4.1   2021-12-13 [1] CRAN (R 4.2.0)
 broom           1.0.0   2022-07-01 [1] CRAN (R 4.2.0)
 cachem          1.0.6   2021-08-19 [1] CRAN (R 4.2.0)
 callr           3.7.0   2021-04-20 [1] CRAN (R 4.2.0)
 cellranger      1.1.0   2016-07-27 [1] CRAN (R 4.2.0)
 class           7.3-20  2022-01-16 [1] CRAN (R 4.2.2)
 classInt        0.4-9   2023-02-28 [1] CRAN (R 4.2.0)
 cli             3.6.1   2023-03-23 [1] CRAN (R 4.2.0)
 codetools       0.2-18  2020-11-04 [1] CRAN (R 4.2.2)
 colorspace      2.1-0   2023-01-23 [1] CRAN (R 4.2.0)
 crayon          1.5.1   2022-03-26 [1] CRAN (R 4.2.0)
 curl            5.0.0   2023-01-12 [1] CRAN (R 4.2.0)
 data.table      1.14.2  2021-09-27 [1] CRAN (R 4.2.0)
 DBI             1.1.3   2022-06-18 [1] CRAN (R 4.2.0)
 dbplyr          2.2.1   2022-06-27 [1] CRAN (R 4.2.0)
 devtools      * 2.4.3   2021-11-30 [1] CRAN (R 4.2.0)
 dplyr         * 1.0.9   2022-04-28 [1] CRAN (R 4.2.0)
 e1071           1.7-13  2023-02-01 [1] CRAN (R 4.2.0)
 ellipsis        0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fansi           1.0.4   2023-01-22 [1] CRAN (R 4.2.0)
 fastmap         1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
 forcats       * 0.5.1   2021-01-27 [1] CRAN (R 4.2.0)
 foreign         0.8-83  2022-09-28 [1] CRAN (R 4.2.2)
 fs              1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
 gdalUtilities * 1.2.4   2023-03-21 [1] CRAN (R 4.2.0)
 generics        0.1.3   2022-07-05 [1] CRAN (R 4.2.1)
 gghighlight   * 0.3.3   2022-06-06 [1] CRAN (R 4.2.0)
 ggplot2       * 3.4.2   2023-04-03 [1] CRAN (R 4.2.0)
 ggrepel       * 0.9.2   2022-11-06 [1] CRAN (R 4.2.0)
 ggsflabel     * 0.0.1   2022-12-12 [1] Github (yutannihilation/ggsflabel@a489481)
 ggspatial     * 1.1.8   2023-04-13 [1] CRAN (R 4.2.0)
 glue            1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
 gtable          0.3.3   2023-03-21 [1] CRAN (R 4.2.0)
 haven           2.5.0   2022-04-15 [1] CRAN (R 4.2.0)
 here          * 1.0.1   2020-12-13 [1] CRAN (R 4.2.0)
 hms             1.1.1   2021-09-26 [1] CRAN (R 4.2.0)
 httr            1.4.3   2022-05-04 [1] CRAN (R 4.2.0)
 jsonlite        1.8.0   2022-02-22 [1] CRAN (R 4.2.0)
 KernSmooth      2.23-20 2021-05-03 [1] CRAN (R 4.2.2)
 lattice         0.20-45 2021-09-22 [1] CRAN (R 4.2.2)
 lifecycle       1.0.3   2022-10-07 [1] CRAN (R 4.2.0)
 lubridate       1.8.0   2021-10-07 [1] CRAN (R 4.2.0)
 magick        * 2.7.3   2021-08-18 [1] CRAN (R 4.2.0)
 magrittr        2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
 memoise         2.0.1   2021-11-26 [1] CRAN (R 4.2.0)
 modelr          0.1.8   2020-05-19 [1] CRAN (R 4.2.0)
 munsell         0.5.0   2018-06-12 [1] CRAN (R 4.2.0)
 openxlsx        4.2.5   2021-12-14 [1] CRAN (R 4.2.0)
 pillar          1.9.0   2023-03-22 [1] CRAN (R 4.2.0)
 pkgbuild        1.3.1   2021-12-20 [1] CRAN (R 4.2.0)
 pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
 pkgload         1.3.0   2022-06-27 [1] CRAN (R 4.2.0)
 prettyunits     1.1.1   2020-01-24 [1] CRAN (R 4.2.0)
 processx        3.6.1   2022-06-17 [1] CRAN (R 4.2.0)
 proxy           0.4-27  2022-06-09 [1] CRAN (R 4.2.0)
 ps              1.7.1   2022-06-18 [1] CRAN (R 4.2.0)
 purrr         * 1.0.1   2023-01-10 [1] CRAN (R 4.2.0)
 qdrmapbox     * 0.1.0   2023-05-06 [1] Github (qdread/qdrmapbox@a7f836d)
 R6              2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 raster        * 3.6-20  2023-03-06 [1] CRAN (R 4.2.0)
 RColorBrewer  * 1.1-3   2022-04-03 [1] CRAN (R 4.2.0)
 Rcpp            1.0.10  2023-01-22 [1] CRAN (R 4.2.0)
 readr         * 2.1.2   2022-01-30 [1] CRAN (R 4.2.0)
 readxl          1.4.0   2022-03-28 [1] CRAN (R 4.2.0)
 remotes         2.4.2   2021-11-30 [1] CRAN (R 4.2.0)
 reprex          2.0.1   2021-08-05 [1] CRAN (R 4.2.0)
 rgdal         * 1.6-2   2022-11-09 [1] CRAN (R 4.2.0)
 rio           * 0.5.29  2021-11-22 [1] CRAN (R 4.2.0)
 rlang           1.1.1   2023-04-28 [1] CRAN (R 4.2.0)
 rprojroot       2.0.3   2022-04-02 [1] CRAN (R 4.2.0)
 rstudioapi      0.13    2020-11-12 [1] CRAN (R 4.2.0)
 rvest           1.0.2   2021-10-16 [1] CRAN (R 4.2.0)
 scales        * 1.2.1   2022-08-20 [1] CRAN (R 4.2.0)
 sessioninfo     1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
 sf            * 1.0-12  2023-03-19 [1] CRAN (R 4.2.0)
 sp            * 1.5-0   2022-06-05 [1] CRAN (R 4.2.0)
 stringi         1.7.6   2021-11-29 [1] CRAN (R 4.2.0)
 stringr       * 1.4.0   2019-02-10 [1] CRAN (R 4.2.0)
 terra           1.6-47  2022-12-02 [1] CRAN (R 4.2.0)
 tibble        * 3.2.1   2023-03-20 [1] CRAN (R 4.2.0)
 tidyr         * 1.2.0   2022-02-01 [1] CRAN (R 4.2.0)
 tidyselect      1.1.2   2022-02-21 [1] CRAN (R 4.2.0)
 tidyverse     * 1.3.1   2021-04-15 [1] CRAN (R 4.2.0)
 tzdb            0.3.0   2022-03-28 [1] CRAN (R 4.2.0)
 units           0.8-2   2023-04-27 [1] CRAN (R 4.2.0)
 usethis       * 2.1.6   2022-05-25 [1] CRAN (R 4.2.0)
 utf8            1.2.3   2023-01-31 [1] CRAN (R 4.2.0)
 vctrs           0.6.2   2023-04-19 [1] CRAN (R 4.2.0)
 withr           2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
 xml2            1.3.3   2021-11-30 [1] CRAN (R 4.2.0)
 zip             2.2.0   2021-05-31 [1] CRAN (R 4.2.0)

 [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library

**Comment by qdread** [comment]
Hi again! I finally got back around to look at this. I believe your problem is that you ran an incomplete version of the `ggplot` code at the end of the blog post. According to your earlier reply, you just ran 

```
ggplot() +
  annotation_spatial(data = mdimage_raster, alpha = 0.9)
```

But this will not work as is because the coordinate system in the default ggplot is not a spatially referenced one. In the [blog post](https://sesync-ci.github.io/blog/mapping-with-Mapbox.html), I have 

```
ggplot() +
  annotation_spatial(data = mdimage_raster, alpha = 0.9) +
  geom_sf(data = st_geometry(md_counties), color = 'white', fill = NA) +
  geom_sf(data = md_cities, aes(color = population), size = 2) +
  coord_sf(crs = 3857) +
  mapbox_logo(xmin = -8870000, xmax = -8820000, ymin = 4535000, ymax = 4590000) +
  annotate('text', x = Inf, y = -Inf, label = '\u00a9 Mapbox \u00a9 OpenStreetMap', hjust = 1, vjust = -1, color = 'white', size = 2) +
  scale_color_viridis_c(trans = 'log10', labels = function(x) format(x, scientific = FALSE))
```

That makes the full plot with the borders of the Maryland counties, locations of cities, and the Mapbox logo and attribution text in the corner (that's necessary to put in any visual that sources data from Mapbox). But I assume from your code that you were trying to just plot the background raster image without any of that other stuff. For that your best bet is to just use the native function `plotRGB()` from the **terra** package (which has replaced the **raster** package since I wrote the original blog post):

```
plotRGB(mdimage_raster)
```

**Comment by hkeys999** [comment]
Hi Quentin,

Thanks again for your attentive replies for your advice working with this fantastic R package you developed. Sorry for delay on my side.

I re-ran everything, and I honestly have no idea what has changed, but it’s working….I also ran your suggestion using plotRGB, which also worked. I was trying to take a “shortcut” in my original question by only sending you the code 

doolo_sat1 <- ggplot() +
  annotation_spatial(data = doolo_image_raster, 
                     alpha = 0.9)

…to avoid a lengthy post, but I see this was necessary to return the desired output. Indeed, I wanted to overlay some shape file data onto the sat image and was getting the error message…below is the pasted, full code — which, at one point, also returned another error message:

"Error in doolo_sat + geom_sf(data = st_geometry(doolo_woredas), color = "white",  : 
  non-numeric argument to binary operator”

Nonetheless, it’s working now. 

Again, many thanks for your time,
H

doolo_sat1 <- ggplot() +
  annotation_spatial(data = doolo_image_raster, 
                     alpha = 0.9) +
  geom_sf(data = st_geometry(doolo_woredas), 
          color = 'white', 
          fill = NA) +
  geom_sf(data=sites1,                       #using visited sites as shapefile
          size = 2,
          shape = 23,
          fill = 'darkred') +
  geom_text(data = sites,                     #using visited sites as dataframe
            (aes(x=longitude,
                 y=latitude,
                 label=name)),
            nudge_x=  sites$x_nudge,
            nudge_y = sites$y_nudge,
            size = 3,
            color = "black",
            fontface = "bold") +
  geom_label(data=sites2,                  #using district names as dataframe 
             (aes(x=longitude,
                  y=latitude,
                  label=name)),
             nudge_x=  sites2$x_nudge,
             nudge_y = sites2$y_nudge) +
  annotation_scale(location = "br", 
                   width_hint = 0.25,
                   bar_cols = c('red', 'white'),
                   pad_y = unit(0.4, "cm"), 
                   pad_x = unit(2.5, "cm"),
                   text_col = 'white') +
  annotation_north_arrow(location = "tl", 
                         pad_y = unit(1, "cm"), 
                         pad_x = unit(1, "cm"), 
                         style = north_arrow_fancy_orienteering(text_col = 'white',
                                                                line_col = 'white',
                                                                fill = 'white')) +
  mapbox_logo(xmin = 41.0, 
              xmax = 41.5, 
              ymin = 9.1,
              ymax = 9.5) +
  annotate('text', 
           x=Inf,
           y=-Inf,
           label = '\u00a9 Mapbox', 
           hjust = 1, 
           vjust = -1, 
           color = 'white', 
           size = 4)+
  theme(axis.title.x=element_blank(),
        axis.title.y = element_blank())

**Comment by qdread** [comment]
Yes, there's a bit of an art to creating a "minimal reproducible example" that still reproduces the relevant error with the least amount of code. Sometimes it's hard to tell exactly which part of your code is causing the error ... Glad it all works now!
